services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "8000:8000"